Error on interface constraint violations (+more...)
Plumbs the spans of where each template argument comes from so that
GetTemplateOf() can make more meaningful errors like:

Error: compiler/tests/errors/template-constrained.nib:38:14:
  takes_hash(Bar());
             ^~~~~ 'Bar' does not satisfy interface constraint 'Hashable'
Note: compiler/tests/errors/template-constrained.nib:28:18:
fn takes_hash[T: Hashable](value: T) -> i32 {
                 ^~~~~~~~ constraint declared here

In a similar vein, the names of types are standardized when printed to
the console with '' around the types and formats that look more like
what other compilers print out (but keeping the "Debug" versions around
for more clarity in logs when debugging the compiler :))

Also added more `lit` tests (now using `diff` instead of `FileCheck` to
simplify the tests and ensure the layout of the ^ is correct).

Used Google Gemini to write the "update_golden_output.sh" to easily
update the golden .out files for `lit`... I hate writing bash. :^)

Probably should break this up more... but it's been a long day. Happy
with the progress!